# Config file for automatic testing at travis-ci.org

language: python

python:
    - 2.7
    - 3.6

before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda3/bin:$PATH
    - conda update --yes conda

    #start x-server
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

    #update PythonPath
    - export PYTHONPATH=$PWD/peakit:$PYTHONPATH
install:
    - conda install --yes pip python=$TRAVIS_PYTHON_VERSION pyqt pyqtgraph lmfit nose -c cprescher
    - pip install coverage

script:
    - nosetests --with-coverage --cover-package=controller,model,widget
